# Generated by Django 3.1.4 on 2020-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('maintainer', models.CharField(max_length=255)),
                ('maintainer_email', models.CharField(max_length=255)),
            ],
        ),
    ]
